### PR TITLE
massive speed up for ipu

### PR DESCRIPTION
**Pull request by Eh2406**
on our data the old code synthesized a bg in 70-80 sec with this change it does it in 2-3 sec, more than 20 times faster.

cc @semcogli

### CODE REVIEW

**Comment by janowicz** [comment]
Very cool!  Looking forward to checking this out.  Like you mentioned in the other pull request, the failing Travis runs are due to the separate issue of deprecated index.diff

**Comment by Eh2406** [comment]
It sounds like we need a version of UDST/urbansim#179. Then I can rebase on top of that. How would you like me to proceed?

**Comment by janowicz** [comment]
Yes, good call.  Thanks.  We'll get a version of urbansim#179 in today, and then notify you so you can rebase.

**Comment by janowicz** [comment]
@Eh2406 The deprecated `diff` has been updated now, and the change is in master:
https://github.com/UDST/synthpop/pull/32

Can you rebase the pull requests when you get the chance?

**Comment by Eh2406** [comment]
I have a meeting, I will rebase when it is done. :-) Thanks.

**Comment by Eh2406** [comment]
@semcogli is also working on making sure it is fast on other work loads, not just ours.

**Comment by semcogli** [comment]
A little more info about this update. If the table size is not big, say less than 2000 columns, the original code actually works faster. However, the frequency table we are dealing here has 32257 columns. In this case, the new code will use much shorter time.

**Comment by janowicz** [comment]
Looks good to me.   I tried synthesis test runs with a couple different recipes, before and after the change above-  and observed a speed-up when using this change in both cases, with the faster speedup coming in the recipe that results in bigger frequency table (in line with the comment above).    I think this trade-off is ok, as I think most operational workloads will tend towards synthesizing with more constraints.

**Pull request merged**
