### PR TITLE
specify the columns to get from pums

### PR DESCRIPTION
**Pull request by Eh2406**
This massively reduced the memory use of our recipe.

looks good to go, thoughts?

### CODE REVIEW

**Comment by Eh2406** [comment]
oops... I will look into the failing tests. Please do not merge until I have a chance.

**Comment by Eh2406** [comment]
@janowicz thoughts? Do you want me to squash the commits? Do you know why testing starter2 works locally but not on travis?

**Comment by janowicz** [comment]
Thanks @Eh2406!  Happy to hear about the reduced memory use.  I'll get a chance to review this and look into those questions later in the week

**Comment by Eh2406** [comment]
Did you have a chance to look at this?

**Comment by janowicz** [comment]
This is a nice change :+1: .  Thanks @Eh2406.  I observed lower memory usage here too.    
One thing users should note is that if they're relying on a particular PUMS variable in the output that is not in `h_pums_cols` / `p_pums_cols`, then they should add that variable to the `_pums_cols` tuple (or join it to the output).

**Comment by Eh2406** [comment]
Do you want me to squash the commits?
How can we make the use of `*_pums_cols` clearer? 
What else should be done before merge?

**Comment by janowicz** [comment]
No need to squash.  I added a comment about `*_pums_cols`.  I think its ready to merge, thanks!

**Comment by janowicz** [comment]
The failed travis tests are related to https://github.com/UDST/synthpop/issues/36 which will be resolved separately.

**Pull request merged**
